version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_1}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${APP_PORT}
    depends_on:
      - db
    volumes:
      - maven-repo:/root/.m2

  db:
    image: postgres:16-alpine
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_PORT: ${POSTGRES_PORT}
     POSTGRES_DATABASE: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-p", "5433"]

volumes:
  db_data:
  maven-repo:


