spring:
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      enabled: true

app:
  open-api:
    server:
      url: http://localhost:8081
      description: API for restaurant management solutions
    info:
      title: Restaurant management solutions
      version: 1.0.0
      description: |
        still need to provide desription for this
      contact:
        name: Aymane El Maini
        email: elmainiaymane03@gmail.com
        url: https://aymaneelmaini.vercel.app
  cloudinary:
    url: ${CLOUDINARY_URL}