name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - "main"
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run docker compose
        run: |
          cd backend
          docker compose up --build -d

      - name: Wait for database to be ready
        run: |
          timeout 30s bash -c 'until pg_isready -h localhost -p 5433; do sleep 1; done'

      - name: Run unit/integration test
        run: mvn verify

      - name: Shut down docker
        run: docker compose down

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ayamneelmaini/restaurant-solutions-backend
          tags: latest
          registry: docker.io
          dockerfile: backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

